---
- name: generate password protection for some sites
  become: yes
  htpasswd: >-
    path=/etc/nginx/.htpasswd
    name={{ pd_user }}
    password={{ item }}
  with_items:
    - "{{ pd_kibana_password }}"
    - "{{ pd_neo4j_password }}"

- name: create nginx config
  become: yes
  template: >-
    src={{ item }}
    dest=/etc/nginx/sites-available/{{ item }}
  notify:
    - restart nginx
  with_items: "{{ pd_nginx_sites }}"

- name: disable default site
  become: yes
  file: >-
    path=/etc/nginx/sites-enabled/default
    state=absent
  notify:
    - restart nginx

- name: enable project site
  become: yes
  file: >-
    dest=/etc/nginx/sites-enabled/{{ item }}
    src=/etc/nginx/sites-available/{{ item }}
    state=link
  notify:
    - restart nginx
  with_items: "{{ pd_nginx_sites }}"

- name: create user for project
  become: yes
  user: name={{ pd_user }} groups=docker append=yes shell=/bin/bash

- name: clone project git repo
  become: yes
  become_user: "{{ pd_user }}"
  git: >-
    repo=https://github.com/tmtxt/clojure-pedigree.git
    dest=/home/{{ pd_user }}/clojure-pedigree
    recursive=yes
    update=no
