---
# setup jekyll server in docker for truongtx blog
- hosts: app1
  vars:
    ansible_user: jekyll

    repo_dir: "{{ ansible_env.HOME }}/tmtxt.github.com"
    container_name: "{{ lookup('env', 'CONTAINER_NAME') | default('jekyll', true) }}"
    jekyll_version: "{{ lookup('env', 'JEKYLL_VERSION') | default('3.8.3', true) }}"
    server_port: "{{ lookup('env', 'SERVER_PORT') | default('4000', true) }}"

  tasks:
    - name: Get current user uid
      command: id -u
      register: user_id_res

    - name: Clone blog repo
      git:
        repo: https://github.com/tmtxt/tmtxt.github.com.git
        dest: "{{ repo_dir }}"

    - name: Start/Restart docker container for jekyll blog
      docker_container:
        name: "{{ container_name }}"
        image: "jekyll/jekyll:{{ jekyll_version }}"
        state: "started"
        restart: yes
        volumes:
          - "{{ repo_dir }}:/srv/jekyll"
        published_ports:
          - "{{ server_port }}:4000"
        command: "jekyll serve -D"
        env:
          JEKYLL_UID: "{{ user_id_res.stdout }}"
