# playbook for setting up my personal Jenkins server

---
- hosts: jenkins
  gather_facts: no

  vars:
    # use this user as sudoer
    ansible_user: tmtxt
    ansible_become_pass: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      39663932616436346331666233626133346261633531663533623338326338663163626133616432
      3262653433393631346337353064363236646438393965310a346530386630343038656166633461
      32316364306531343635663037376434643334663732353961653066393435373830306461643364
      3330316138393866370a363562326430646430613338646366393363303032643034336132326535
      3136

  roles:
    - role: init

    - role: swapfile
      become: True
      vars:
        swapfile_size: 2G
        swapfile_swappiness: 10
        swapfile_vfs_cache_pressure: 50

  tasks:
    - name: Install Open JDK 11
      apt: name=openjdk-11-jdk
      become: True

    - name: Add apt key for Jenkins
      become: True
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present

    - name: Add Jenkins apt repo
      become: true
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian binary/
        state: present
        update_cache: true

    - name: Install Jenkins
      become: true
      apt: name=jenkins
      notify:
        - Restart Jenkins

  handlers:
    - name: Restart Jenkins
      become: True
      service:
        name: jenkins
        state: restarted