---
# personal use
- hosts: all
  roles:
    - role: init

    - role: personal
      ssh_user: tmtxt

    - role: swapfile
      become: yes
      swapfile_size: 2G
      swapfile_swappiness: 10
      swapfile_vfs_cache_pressure: 50

    - role: oraclejdk

# docker
- hosts: all
  roles:
    - role: docker
      become: yes
  tasks:
    - name: stop docker from messing iptables rules
      become: yes
      lineinfile: >-
        dest=/etc/default/docker
        line="DOCKER_OPTS=\"--dns 8.8.8.8 --dns 8.8.4.4 --iptables=false\""
      notify:
        - restart docker
  handlers:
    - name: restart docker
      become: yes
      service: name=docker state=restarted

# firewall
- hosts: all
  roles:
    - role: ufw

# projects
- hosts: all
  roles:
#     - role: jenkins
#       jenkins_port: 9250
#       jenkins_site_name: jenkins
#       jenkins_server_name: build.truongtx.me
#       jenkins_server_port: "{{ jenkins_port }}"

    - role: clojure-pedigree
      pd_site_name: clojure_pedigree
      pd_server_name: giapha.truongtx.me
      pd_server_port: 3000
      pd_user: pedigree

    - role: jekyll-docker
      jd_site_name: jekyll_docker
      jd_server_name: jekyll.truongtx.me
      jd_server_port: 17845
      jd_user: jekyll
