---
# setup for personal user
- hosts: all
  roles:
    - role: init

    - role: personal
      ssh_user: tmtxt

    - role: swapfile
      become: true
      swapfile_size: 2G
      swapfile_swappiness: 10
      swapfile_vfs_cache_pressure: 50

    - role: oraclejdk

    - role: ufw

    - role: jenkins
      jenkins_port: 9250
      jenkins_site_name: jenkins
      jenkins_server_name: build.truongtx.me
      jenkins_server_port: "{{ jenkins_port }}"

    - role: clojure-pedigree
      pd_site_name: clojure_pedigree
      pd_server_name: giapha.truongtx.me
      pd_server_port: 9251
