---
# setup for personal user
- hosts: all
  roles:
    - role: personal
      ssh_user: tmtxt

    - role: swapfile
      become: true
      swapfile_size: 2G
      swapfile_swappiness: 10
      swapfile_vfs_cache_pressure: 50
