---
# setting up and running a new minecraft server
- hosts: p1
  gather_facts: no
  vars:
    ansible_user: tmtxt

    # common variables
    minecraft_version: "{{ lookup('env', 'MINECRAFT_VERSION') | default('1.13', true) }}"

    # variables for locating files in host server
    # the default server dir path in jenkins
    default_server_dir: "{{ lookup('env', 'DEFAULT_SERVER_DIR') | default('~/tmtxt/mc-server-default', true) }}"

    # variables for locating files on remote server
    # the dest server dir in the remote host
    server_dir: "{{ lookup('env', 'SERVER_DIR') | default('~/minecraft-server', true) }}"
    container_name: "{{ lookup('env', 'CONTAINER_NAME') | default('minecraft', true) }}"
    container_state: "{{ lookup('env', 'CONTAINER_STATE') | default('started', true) }}"
    server_port: "{{ lookup('env', 'SERVER_PORT') | default('25565', true) }}"
    map_port: "{{ lookup('env', 'MAP_PORT') | default('25566', true) }}"

    # variables used for backup

  tasks:
    - name: Create directory for server
      tags: ['bootstrap', 'setup']
      file:
        path: "{{ server_dir }}"
        state: directory
        mode: 0755

    # Copy server default data
    - name: Copy default server files
      tags: ['bootstrap', 'setup']
      synchronize:
        src: "{{ default_server_dir }}/{{ minecraft_version }}/"
        dest: "{{ server_dir }}/"

    - name: Run minecraft server
      tags: ['run', 'setup']
      docker_container:
        name: "{{ container_name }}"
        image: "openjdk:8-jre"
        state: "{{ container_state }}"
        volumes:
          - "{{ server_dir }}:/minecraft-server"
        published_ports:
          - "{{ server_port }}:25565"
          - "{{ map_port }}:8123"
        working_dir: "/minecraft-server"
        command: java -Xms4G -Xmx4G -XX:+UseConcMarkSweepGC -jar spigot-{{ minecraft_version }}.jar
        tty: yes
        interactive: yes

# Tasks for backing server data, make sure to turn off the server first
- hosts: p1
  gather_facts: no
  tags: ['backup']

  vars:
    ansible_user: tmtxt
    server_dir: "{{ lookup('env', 'SERVER_DIR') | default('~/minecraft-server', true) }}"

  tasks:
    - name: Create temp dir for backup file
      tempfile:
        state: directory
      register: temp_dir

    - debug: msg={{ temp_dir.path }}

    - name: Backup server data
      tags: ['backup']
      shell: >-
        zip -r -0 \
        --exclude='*plugins/dynmap/*' \
        minecraft-$(date +%FT%R).zip \
        {{ server_dir }}
      args:
        chdir: "{{ temp_dir.path }}"
      ignore_errors: yes
      register: zip_res

    - name: Cleanup temp dir
      file:
        path: "{{ temp_dir.path }}"
        state: absent

    - name: Check zip result
      fail: msg="Fail to create zip file"
      when: zip_res.failed
