---
- name: create nginx config
  become: yes
  template: >-
    src=nginx-site
    dest=/etc/nginx/sites-available/{{ jd_site_name }}
  notify:
    - restart nginx

- name: disable default site
  become: yes
  file: >-
    path=/etc/nginx/sites-enabled/default
    state=absent
  notify:
    - restart nginx

- name: enable project site
  become: yes
  file: >-
    dest=/etc/nginx/sites-enabled/{{ jd_site_name }}
    src=/etc/nginx/sites-available/{{ jd_site_name }}
    state=link
  notify:
    - restart nginx

- name: create user for project
  become: yes
  user: name={{ jd_user }} groups=docker append=yes shell=/bin/bash

- name: clone project git repo
  become: yes
  become_user: "{{ jd_user }}"
  git: >-
    repo=https://github.com/tmtxt/jekyll-docker-compose.git
    dest=/home/{{ jd_user }}/website
    recursive=yes
    update=no

- name: clone blog
  become: yes
  become_user: "{{ jd_user }}"
  git: >-
    repo=https://github.com/tmtxt/tmtxt.github.com.git
    dest=/home/{{ jd_user }}/website/blog
    recursive=yes
    update=yes
