---
- name: create nginx config
  become: yes
  template: >-
    src=nginx-site
    dest=/etc/nginx/sites-available/{{ aria2_site_name }}
  notify:
    - restart nginx

- name: disable default site
  become: yes
  file: >-
    path=/etc/nginx/sites-enabled/default
    state=absent
  notify:
    - restart nginx

- name: enable project site
  become: yes
  file: >-
    dest=/etc/nginx/sites-enabled/{{ aria2_site_name }}
    src=/etc/nginx/sites-available/{{ aria2_site_name }}
    state=link
  notify:
    - restart nginx
