---
- name: Create home folder for Jenkins
  become: yes
  file:
    path: "{{ jenkins_home_dir }}"
    state: directory
    owner: 1000

- name: Start container for Jenkins server
  docker_container:
    name: "{{ jenkins_container_name | default('jenkins') }}"
    image: "{{ jenkins_image }}"
    state: "{{ jenkins_container_state }}"
    volumes:
      - "{{ jenkins_home_dir }}:/var/jenkins_home"
    published_ports:
      - "{{ jenkins_server_port }}:8080"

- name: Create nginx config file
  become: true
  when: setup_nginx
  template: >-
    src=nginx-site
    dest=/etc/nginx/sites-available/{{ jenkins_site_name }}
  notify:
    - Restart nginx

- name: Symlink config file
  become: true
  when: setup_nginx
  file: >-
    dest=/etc/nginx/sites-enabled/{{ jenkins_site_name }}
    src=/etc/nginx/sites-available/{{ jenkins_site_name }}
    state=link
  notify:
    - Restart nginx
